Commit

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -37,10 +37,20 @@ jobs:
 
       - name: Fetch the gh-pages branch
         run: git fetch origin gh-pages --depth=1
+      
+      - name: List files in gh-pages branch
+        run: |
+          git checkout gh-pages
+          ls -la
 
       - name: Deploy latest documentation version
         if: env.Deploy_Type == 'release'
-        run: mike deploy $Version latest --update-aliases --branch gh-pages
+        run: |
+          mike deploy $Version latest --update-aliases --branch gh-pages
+          if [ $? -ne 0 ]; then
+            echo "Mike deploy failed"
+            exit 1
+          fi
 
       - name: Set default version to latest
         if: env.Deploy_Type == 'release'
@@ -49,4 +59,3 @@ jobs:
       - name: Deploy indev documentation
         if: env.Deploy_Type == 'indev'
         run: mike deploy $Version --push --update-aliases --branch gh-pages
-        
